-- CREATE TABLE BANTRAB_EMPLOYEE (
--   ID INT,
--   NAME VARCHAR(50),
--   ADDRESS VARCHAR(50),
--   PRIMARY KEY (ID)
-- );

-- INSERT INTO BANTRAB_EMPLOYEE (ID, NAME, ADDRESS)
-- VALUES (1, 'Andres', 'Ciudad');

SELECT * FROM BANTRAB_EMPLOYEE;